### ISSUE TITLE
conan install doesn't work

### ISSUE THREAD

**Issue by lemaxw** [antlad/nats_asio#2]
when I execute 
conan install --build=missing
get following:
cxxopts/v2.1.2@inexorgame/stable: Not found in local cache, looking in remotes...
cxxopts/v2.1.2@inexorgame/stable: Trying with 'conan-center'...
ERROR: Unable to find 'cxxopts/v2.1.2@inexorgame/stable' in remotes

Tried on both windows 10 and ubunta 18.04
searching for suitable libs, doesn't find any:
>conan search cxxopts/* -r=all
>There are no packages matching the 'cxxopts/*' pattern

**Comment by antlad** [comment]
@lemaxw Sorry, just noticed issue. Try look in config_conan.sh . It is attaching all needed remotes. But it is more sample to what you can do in your project - I decided to do it headers only for now(maybe later on I'll do compiled library with conan isntall).
